### ISSUE TITLE
Not able to set adb path

### ISSUE THREAD

**Issue by amalChandran** [yapplications/ADB-GUI#1]
Hey looks like a promising tool this.

However, I am not able to add my adb path to the startup check dialog. I keep getting no adb found, try different path.

Running this on a mac.

**Comment by kirvis250** [comment]
I used this "C:\Android\sdk\platform-tools\"  --> "...ools\" see that sneaky seperator?
So most likely you didn't added file separator after last path segment. 

I had to download and compile the code myself to realize that i was entering "C:\Android\sdk\platform-tools" and not "C:\Android\sdk\platform-tools\". 😄

**Comment by amalChandran** [comment]
The solution is opposite in mac. I had to add "/" at the end of the path. Thanks :)

**Comment by evgeni-shafran** [comment]
@amalChandran thanks for the input :) i just uploaded a version (0.1.9v) where you don't have to add the '/' in the end :) and also added support to '/adb' ending.

@kirvis250 thanks for the help :)
