### ISSUE TITLE
Uninstall android applications as user 0 possibility

### ISSUE THREAD

**Issue by ozon85** [yapplications/ADB-GUI#8]
Hello.
If I'm going to delete the system app from my xiaomi phone I get an error:
  adb shell pm uninstall com.android.browser
  Failure [DELETE_FAILED_INTERNAL_ERROR]

However, adding the --user 0 parameter solves this problem:
  adb shell pm uninstall --user 0 com.android.browser
  Success

The hint is taken from here:
https://stackoverflow.com/questions/59795600/adb-failure-delete-failed-internal-error

**Comment by Makstuff** [comment]
Why did you mark this as completed? I have exactly the same problem right now, and can't find any option or anything in the GUI, so if there's a working solution it would be cool to add it here.

**Comment by ozon85** [comment]
After creating my message, I found out that adding the username flag does not actually delete the application, but leaves it in the system. Although it becomes unavailable to all users, after resetting the system settings, the application will recover.
Therefore, I felt that my request was not entirely correct and, in principle, did not correspond to my wishes.

**Comment by Makstuff** [comment]
Hmm, that's interesting. I guess in practice I personally don't care all that much, since what I actually want is remove clutter icons from my app drawer, for which it seems to do the job as long as I leave the reset button alone.
